#!/bin/sh

# Setup with pod with local dir bind mounts for data persistence

set -x

podman pod create \
  --name my-postgraphile \
  --userns=keep-id \
  -p 8080:8080 ;

# podman network create my-postgraphile-net;
            # --network my-postgraphile-net \

# podman volume create my_postgraphile_data;

podman run --name my-postgraphile-db \
    -e POSTGRES_PASSWORD=postgre108 \
    -e POSTGRES_USER=postgraphile \
    -e POSTGRES_DB=postgraphile \
    -v $PWD/my_postgraphile_data:/var/lib/postgresql/data:Z \
    --pod my-postgraphile \
    -d \
    postgres:16;

podman build -t my-postgraphile-app ./app;

podman run --name my-postgraphile-app \
    -v ./volume:/home/node/app/volume:Z \
    -e DATABASE_URL=postgres://postgraphile:postgre108@localhost:5432/postgraphile \
    -e GRAPHILE_ENABLE_CONSOLE=true \
    -e GRAPHILE_ENABLE_GRAPHIQL=true \
    -e GRAPHILE_SCHEMA=public \
    --pod my-postgraphile \
    -d \
    my-postgraphile-app sleep infinity;

podman generate kube my-postgraphile > my-postgraphile-pod.yaml;