#!/bin/sh

# Setup with pod with local dir bind mounts for data persistence

set -x

podman pod create \
  --name my-postgraphile \
  --userns=keep-id \
  -p 8080:8080 \
  -p 5678:5678;

podman run \
    --name my-postgraphile-db \
    -e POSTGRES_PASSWORD=postgre108 \
    -e POSTGRES_USER=postgraphile \
    -e POSTGRES_DB=postgraphile \
    -v $PWD/my_postgraphile_data:/var/lib/postgresql/data:Z \
    --pod my-postgraphile \
    -d \
    postgres:16;

podman run \
    --name my-postgraphile-adminer \
    --pod my-postgraphile \
    -d \
    adminer;

podman build \
  --no-cache \
  -t my-postgraphile-app \
  --target=build \
  ./app;

podman run \
    --name my-postgraphile-app \
    -v ./volume:/home/node/app/volume:Z \
    -v ./app/src:/home/node/app/src:Z \
    -e DATABASE_URL=postgres://postgraphile:postgre108@localhost:5432/postgraphile \
    -e GRAPHILE_ENV=development \
    -e GRAPHILE_ENABLE_CONSOLE=true \
    -e GRAPHILE_ENABLE_GRAPHIQL=true \
    -e GRAPHILE_SCHEMA=public \
    --pod my-postgraphile \
    --workdir /home/node/app \
    --init \
    -it \
    my-postgraphile-app;

# podman generate kube my-postgraphile > my-postgraphile-pod.yaml;

# podman exec -it my-postgraphile-app bash;

podman pod stop my-postgraphile;
podman pod rm my-postgraphile;