#!/bin/sh

# Setup with pod with local dir bind mounts for data persistence

set -x

mkdir -p ./db/db-data
if [ ! -f ./db/.env ]; then cp ./db/template.env ./db/.env; fi
if [ ! -f ./db/pass_file ]; then cp ./db/pass_file.template ./db/pass_file; fi
if [ ! -f ./app/.env ]; then cp ./app/template.env ./app/.env; fi

podman secret create pg_pass ./db/pass_file

podman pod create \
  --name my-postgraphile \
  --userns=keep-id \
  -p 8080:8080 \
  -p 5678:5678;

podman run \
    --name my-postgraphile-db \
    --env-file ./db/.env \
    --secret=pg_pass \
    -v $PWD/db/db-data:/var/lib/postgresql/data:Z \
    --pod my-postgraphile \
    -d \
    postgres:17;

podman run \
    --name my-postgraphile-adminer \
    --pod my-postgraphile \
    -d \
    adminer;

podman build \
  --tag my-postgraphile-app \
  --target=build \
  ./app;

podman run \
    --name my-postgraphile-app \
    -v ./volume:/home/node/app/volume:Z \
    -v ./app/src:/home/node/app/src:Z \
    --env-file ./app/.env \
    --pod my-postgraphile \
    --init \
    -it \
    my-postgraphile-app;

# podman generate kube my-postgraphile > my-postgraphile-pod.yaml;

# podman exec -it my-postgraphile-app bash;

podman pod stop my-postgraphile;
podman pod rm my-postgraphile;
podman secret rm pg_pass;